- hosts: all
  tasks:
    - name: Run a command under cmd
      win_shell: rclone copy --progress --buffer-size=16M C:\Users\Administrator\videosc5 AWS_S3:c2pruebayair2023/test23 --log-file c:\Users\Administrator\sync_files2.txt
      args:
        executable: cmd.exe
    - name: Run an executable using win_command
      win_command: whoami.exe
