- hosts: all
  tasks:
    - name: Run a command under cmd
      win_shell: mkdir C:\temp
      args:
        executable: cmd.exe
    - name: Run an executable using win_command
      win_command: whoami.exe
